(import (chezscheme))
(load "host/chez/gate-boot.ss")
(define sink #f)
(define (measure n label)
  (collect (collect-maximum-generation))
  (let ((b (bytes-allocated)))
    (do ((i 0 (+ i 1))) ((= i 100)) (set! sink (na-byte-array n)))
    (let ((d (- (bytes-allocated) b)))
      (printf "~a (byte-array ~a) x100 = ~a bytes\n" label n d)
      d)))
(let ((d1000 (measure 1000 "")) (d0 (measure 0 "")))
  (printf "  net backing: ~a bytes -> ~,2f bytes/element\n"
          (- d1000 d0) (/ (- d1000 d0) 100000.0)))
;; round-trip cost of the raw-byte seam
(let ((a (na-byte-array 4096)))
  (collect (collect-maximum-generation))
  (let ((b (bytes-allocated)))
    (do ((i 0 (+ i 1))) ((= i 100)) (set! sink (na-bytearray->bv a)))
    (printf "na-bytearray->bv 4096 x100 = ~a bytes\n" (- (bytes-allocated) b))))
