#!/usr/bin/env python3
import subprocess, os
D = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CCBY = "CC-BY 4.0"
P = [
 ("PLDI22-flexible-type-system-for-fearless-concurrency",
  "A Flexible Type System for Fearless Concurrency",
  "Mae Milano, Julia Turcotti, Andrew C. Myers. PLDI 2022. doi:10.1145/3519939.3523443",
  "https://doi.org/10.1145/3519939.3523443", CCBY),
 ("flo-semantic-foundation-progressive-stream-processing",
  "Flo: A Semantic Foundation for Progressive Stream Processing",
  "Shadaj Laddad, Alvin Cheung, Joseph M. Hellerstein, Mae Milano. POPL 2025. doi:10.1145/3704845",
  "https://doi.org/10.1145/3704845", CCBY),
 ("POPL24-soundly-handling-linearity",
  "Soundly Handling Linearity",
  "Wenhao Tang, Daniel Hillerstrom, Sam Lindley, J. Garrett Morris. POPL 2024. doi:10.1145/3632896",
  "https://arxiv.org/abs/2307.09383", CCBY + " (arXiv posting)"),
 ("POPL19-exceptional-asynchronous-session-types",
  "Exceptional Asynchronous Session Types: Session Types without Tiers",
  "Simon Fowler, Sam Lindley, J. Garrett Morris, Sara Decova. POPL 2019. doi:10.1145/3290341",
  "https://homepages.inf.ed.ac.uk/slindley/papers/zap.pdf", CCBY + " (Crossref)"),
 ("POPL18-rustbelt-securing-the-foundations-of-rust",
  "RustBelt: Securing the Foundations of the Rust Programming Language",
  "Ralf Jung, Jacques-Henri Jourdan, Robbert Krebbers, Derek Dreyer. POPL 2018. doi:10.1145/3158154",
  "https://plv.mpi-sws.org/rustbelt/popl18/paper.pdf", CCBY + " (Crossref)"),
 ("OOPSLA20-how-do-programmers-use-unsafe-rust",
  "How Do Programmers Use Unsafe Rust?",
  "Vytautas Astrauskas, Christoph Matheja, Federico Poli, Peter Mueller, Alexander J. Summers. OOPSLA 2020. doi:10.1145/3428204",
  "https://pm.inf.ethz.ch/publications/AstrauskasMathejaMuellerPoliSummers20.pdf", CCBY + " (Crossref)"),
 ("ICFP20-liquid-resource-types",
  "Liquid Resource Types",
  "Tristan Knoth, Di Wang, Adam Reynolds, Jan Hoffmann, Nadia Polikarpova. ICFP 2020. doi:10.1145/3408988",
  "https://www.cs.cmu.edu/~janh/assets/pdf/WangKRPH20.pdf", CCBY + " (Crossref)"),
 ("ICFP21-client-server-sessions-in-linear-logic",
  "Client-Server Sessions in Linear Logic",
  "Zesen Qian, G. A. Kavvos, Lars Birkedal. ICFP 2021. doi:10.1145/3473567",
  "https://pure.au.dk/ws/files/285414161/3473567.pdf", CCBY + " (Crossref; also in PDF)"),
 ("PLDI23-flux-liquid-types-for-rust",
  "Flux: Liquid Types for Rust",
  "Nico Lehmann, Adam T. Geller, Niki Vazou, Ranjit Jhala. PLDI 2023. doi:10.1145/3591283",
  "https://ranjitjhala.github.io/static/flux-pldi23.pdf", CCBY),
 ("ICFP19-quantitative-program-reasoning-with-graded-modal-types",
  "Quantitative Program Reasoning with Graded Modal Types",
  "Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III. ICFP 2019. doi:10.1145/3341714",
  "https://www.cs.kent.ac.uk/people/staff/dao7/publ/granule-icfp19.pdf", CCBY),
 ("POPL20-linear-haskell",
  "Linear Haskell: Practical Linearity in a Higher-Order Polymorphic Language",
  "Jean-Philippe Bernardy, Mathieu Boespflug, Ryan R. Newton, Simon Peyton Jones, Arnaud Spiwack. POPL 2018. doi:10.1145/3158093",
  "https://arxiv.org/abs/1710.09756", CCBY + " (arXiv posting)"),
 ("CONCUR20-session-types-with-arithmetic-refinements",
  "Session Types with Arithmetic Refinements",
  "Ankush Das, Frank Pfenning. CONCUR 2020. doi:10.4230/LIPIcs.CONCUR.2020.13",
  "https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.CONCUR.2020.13", "CC-BY (LIPIcs)"),
 ("COORDINATION14-affine-sessions",
  "Affine Sessions",
  "Dimitris Mostrous, Vasco Thudichum Vasconcelos. COORDINATION/DisCoTec 2014. doi:10.1007/978-3-662-43376-8_8",
  "https://inria.hal.science/hal-01290071", CCBY + " (HAL deposit)"),
 ("dependent-multiplicities-in-dependent-linear-type-theory",
  "Dependent Multiplicities in Dependent Linear Type Theory",
  "Maximilian Dore. 2026.",
  "https://arxiv.org/abs/2507.08759", CCBY),
 ("grounded-conceptual-model-for-ownership-types-in-rust",
  "A Grounded Conceptual Model for Ownership Types in Rust",
  "2023.",
  "https://arxiv.org/abs/2309.04134", CCBY + " (arXiv posting)"),
]
os.makedirs(f"{D}/markdown", exist_ok=True)
for stem, title, cite, src, lic in P:
    pdf = f"{D}/{stem}.pdf"
    dest = f"{D}/markdown/{stem}.md"
    r = subprocess.run(["python3", os.path.join(os.path.dirname(os.path.abspath(__file__)), "convert.py"), pdf, title, cite, src, lic, dest],
                       capture_output=True, text=True)
    print(f"{stem[:52]:54s} {r.stdout.strip() or r.stderr.strip()[:70]}")
